### ISSUE TITLE
Problem Getting Internal Storage and External Storage paths

### ISSUE THREAD

**Issue by zahoribello** [smartdevelopers-ir/SmartFilePicker#14]
Hello again, I am having a problem Obtaining the Internal Storage and External Storage paths, which does not happen with Download or the Recent Files list. Example:

Internal Storage => content://com.android.providers.media.documents/document/document%3A1000034680
External Storage => content://com.android.providers.media.documents/document/document%3A1000034680
Download => content://pdfreader.pdfviewer.documentreader.officetool.sfb_provider/sfb_files/Download/example.pdf
Recent Files List => content://pdfreader.pdfviewer.documentreader.officetool.sfb_provider/sfb_images/Screenshot/Screenshot_20230609-194409.jpg

I'm using Android 13:

distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip

plugins {
     id 'com.android.application' version '8.0.0' apply false
     id 'com.android.library' version '8.0.0' apply false
     id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
}

Using Kotlin, in my project. I hope you can help me with this inconvenience.

**Comment by smartdevelopers-ir** [comment]
Hello. I can't understand what you want exactly. You can't get external or internal storage file path with this library. It just obtain you selected files Uris with SmartFilePicker.getResultUris(data) in onActivityResult callback. Then you can using these Uris with ContentResolver API
